create table if not exists users
(
    id    bigint generated by default as identity
        primary key,
    email varchar(255)
        constraint uk_email_user
            unique,
    name  varchar(64)
);

create table if not exists locations
(
    id  bigint generated by default as identity
        primary key,
    lat real not null,
    lon real not null
);

create table if not exists categories
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
        constraint uk_name_category
            unique
);

create table if not exists events
(
    id                 bigint generated by default as identity
        primary key,
    annotation         varchar(1024) not null,
    available          boolean,
    confirmed_requests integer not null,
    created_on         timestamp,
    description        varchar(2056),
    event_date         timestamp not null,
    paid               boolean not null,
    participant_limit  integer,
    published_on       timestamp,
    request_moderation boolean,
    state              varchar(255),
    title              varchar(1024) not null,
    views              bigint  not null,
    category_id        bigint
        constraint fk_events_categories
            references categories,
    initiator_id       bigint
        constraint fk_events_users
            references users,
    location_id        bigint
        constraint fk_events_locations
            references locations
);

create table if not exists requests
(
    id           bigint generated by default as identity
    primary key,
    created      timestamp,
    status       varchar(255),
    event_id     bigint
    constraint fk_requests_events
    references events,
    requester_id bigint
    constraint fk_request_users
    references users
    );

create table if not exists compilations
(
    id     bigint generated by default as identity
        primary key,
    pinned boolean,
    title  varchar(255)
);

create table if not exists compilations_events
(
    compilation_id bigint not null
        constraint fk_compilations
            references compilations,
    events_id      bigint not null
        constraint fk_events
            references events
);