version: '3.1'
services:
  stats-server:
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine

  ewm-service:
    depends_on:
      - stats-server
      - ewm-db
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
