version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats-server-image
    container_name: stats-server-container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=me

  stats-db:
    image: postgres:14.4-alpine
    container_name: stats-db-container
    volumes:
      - stats-db:/var/lib/postgresql/data
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=me

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    depends_on:
      - stats-server
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - EXPLORE_WITH_ME_STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=with

  ewm-db:
    image: postgres:14.4-alpine
    container_name: ewm-db-container
    volumes:
      - ewm-db:/var/lib/postgresql/data
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=with

volumes:
  ewm-db:
  stats-db: