create table if not exists hits
(
    id        bigint generated by default as identity
        primary key,
    app       varchar(255) not null,
    ip        varchar(255) not null,
    timestamp timestamp not null,
    uri       varchar(255) not null
);